############################
#       LOCAL
############################

spring:
  profiles: local
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

server:
  port: 8080

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: mca-realm.json

---

############################
#       PROD
############################
spring:
  profiles: production
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

server:
  port: 8080

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: mca-realm.json